services:
  # =========================
  # Kafka (Bitnami, KRaft)
  # =========================
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:29092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT_HOST://:9092,PLAINTEXT_INTERNAL://:29092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT_INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT_HOST:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks: [knet]
    volumes:
      - kafka_data:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka
    networks: [knet]

  # =========================
  # Indexer app (monorepo: apps/indexer-server)
  # =========================
  indexer:
    container_name: indexer
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PATH: ./apps/indexer-server
    env_file: ./apps/indexer-server/.env
    environment:
      # Make sure your code reads this:
      - KAFKA_BROKERS=kafka:29092
      - NODE_ENV=production
      # If you use Prisma:
      # - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/sol
      # Yellowstone etc.:
      # - GRPC_ENDPOINT=${GRPC_ENDPOINT}
    depends_on:
      kafka:
        condition: service_healthy
    networks: [knet]
    # Dev hot-reload (optional):
    # volumes:
    #   - ./apps/indexer-server:/app
    #   - /app/node_modules

  # Workers/commands using the same image
  producer-sol:
    extends: { service: indexer }
    container_name: producer-sol
    environment:
      MODE: "sol"
    command: ["node","dist/workers/producer.js"]
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

  consumer:
    extends: { service: indexer }
    container_name: consumer
    command: ["node","dist/workers/consumer.js"]
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

  # =========================
  # API server (monorepo: apps/api-server)
  # =========================
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PATH: ./apps/api-server
    env_file: ./apps/api-server/.env
    environment:
      # App basics
      - NODE_ENV=production
      - PORT=3000
      # Auth
      - API_SECRET=${API_SECRET:-change_me_api_secret}
      - JWT_SECRET=${JWT_SECRET:-change_me_jwt_secret}
      # Rate limit (Redis)
      - REDIS_URL=redis://redis:6379
      # If your API reads Kafka:
      - KAFKA_BROKERS=kafka:29092
      # If you need CORS:
      - CORS_ORIGIN=*
    ports:
      - "3000:3000"
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/healthz || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks: [knet]
    restart: unless-stopped
    # volumes (dev hot-reload example):
    # volumes:
    #   - ./apps/api-server:/app
    #   - /app/node_modules
    # command: ["npm","run","dev"]

networks:
  knet:

volumes:
  kafka_data:
